---
title: "Resume"
output:
  html_document
---

## Education

**Master of Science, Columbia University, Mailman School of Public Health, New York, NY, 2019**   
Major: Biostatisitcs (Theory & Methods track); GPA: 3.75/4.0  

**Bachelor of Science, Shanghai Jiao Tong University (SJTU), Shanghai, China, 2017**  
Major: Pharmacy, Minor: Musicology; GPA: 3.5/4.0  
  
  
## Professional Experience 

**Research Assistant – Data Analyst, School of Nursing, Columbia University, New York, NY**  
  
* Utilized descriptive statistics and statistical models in analyzing survey and CMS (Medicaid & Medicare) data using SAS & STATA
* Streamlined and improved performance and accuracy of questionnaire using factor analysis(EFA, CFA) and IRT (Item Response Theory) model
* Summarized exhibits, tables and figures in Excel using Pivot Tables and prepared the final paper for review
* Served as a main contributor in drafting protocols for data collection and data processing methods and collaborated with other researchers on data management, statistical analysis plan (SAP) and manuscript preparation  
* Recognized for formatting 40+ research papers in alignment with APA, AMA and Chicago Manual of Style guidelines
  
**Modeling Analyst Intern, BroadRiver Asset Management, L.P., New York, NY**  

* Expertly supported a project team of 7 to develop a medical questionnaire using qualitative and quantitative methods
* Conducted literature review of 122 articles on long-term mortality of seniors based on certain diseases & lifestyles and designed 327 questions with supporting scoring algorithm to estimate the survival rate of insured client in Python
* Managed and optimized large-scale life settlement dataset to track client outcomes and build portfolio efficiently
* Manipulated and analyzed third-party underwriting data to facilitate strategic decision and save cost for the firm  
* Skillfully performed survival modeling to identify differences between clients’ self-reported and actual health status  
* Precisely completed comprehensive financial modeling to generate business insights using V-Lookup in Excel
  
**Assistant Analyst, IlluminHealth, The Illuminera Group, Shanghai, China**  
  
* Conducted target data collection routinely through literature and database in each internal and external project  
* Synthesized different types of data (continuous & categorical) and performed data analysis using Excel with VBA  
* Assisted the final report and presentation of different market research projects by designing PowerPoint slides
* Drafted questionnaires to ensure alignment with customized requirements of multiple clients from various healthcare companies while participated in the in-depth interviews with 5+ physicians to acquire corresponding information

## Additional Experience

**Teaching Assistant, Data Science 1, Dept. of Biostatistics, Columbia University, New York, NY**  
  
* Facilitated outstanding support for a class of 150+ students and administered student-centered coaching, mentoring and development along with in-depth feedback to improve performance and abilities in data science skills
  
**Project Leader, Data Science 2, Dept. of Biostatistics, Columbia University, New York, NY**  
  
* Preprocessed the database (3700000 rows) and screened 9 features for further regression & classification analysis
* Performed exploratory data analysis and data visualization to the dataset via ggplot2, plot.ly and Shiny in R
* Evaluated the performance of different machine learning methods (Random Forest, SVM, Gradient Boosting, etc.)  

**Research Assistant, Dept. of Bioinformatics & Biostatistics, SJTU, Shanghai, China**  
  
* Extracted and filtered phosphorylated protein data from CPTAC databases (10062 proteins, 51122 phosphosites)
* Strategized on best usage of distance correlation model and successfully assessed model fit for research question
* Applied the latest statistical model to the clinical data (77 patients) and analyzed results using R and Excel  

**Research Associate, Microfluidics Lab, University of Illinois at Chicago, Chicago, IL**  
  
* Earned a stellar reputation for designing investigational projects on microfluidics biomedical devices while closely coordinating with a team of 3, thus streamlining experimental processes and enhancing efficiency by 25%

## Leadership Experience

**Principal Trombone**, Columbia Univserivty Symphony Orchestra, Columbia University  
**Vice President**, Chinese Students & Scholars Association, Columbia University Medical Center 

## Personal Skills  

**Statistical & Computing software**: SAS, R, STATA, SPSS, SQL, Python, MATLAB, Mplus, Microsoft Office: Excel (VBA), Access and PowerPoint  
**Languages** : Mandarin (native) and English (fluent)



